resolution_width = 960;
resolution_height = 640;
resolution_scale = 2;
global.view_witdh = resolution_width / resolution_scale;
global.view_height = resolution_height / resolution_scale;
view_target = obj_player;
view_spd = 0.1;
window_set_size(global.view_witdh * resolution_scale, global.view_height * resolution_scale);
surface_resize(application_surface, global.view_witdh * resolution_scale, global.view_height * resolution_scale);
display_set_gui_size(global.view_witdh, global.view_height);